version: 1 # This is the version of the schema file format

sources:
  - name: debezium # this is the source_name
    database: augmented-world-456406-m8 # this is the project_name
    description: "This source contains the raw data from the Debezium CDC connector."
    # The schema_name is the schema where the source tables are located.
    # In this case, it is the same as the database_name.
    # If you are using a different schema, you can specify it here.
    schema: debezium # this is the schema_name

    tables:
      - name: customers # this is the table_name
        description: "This table contains customer data."
      - name: orders
        description: "This table contains order data."
      - name: products
        description: "This table contains product data."
      - name: order_items
        description: "This table contains order item data."

models:
  - name: stg_debezium_customers  # this must match the model name (not file name)
    description: "This model contains email addresses extracted from the customers table."
    columns:
      - name: first_name
        description: "The first name of the customer."
        tests:
          - first_name_not_empty
      - name: email
        description: "The email address of the customer."
        tests:
          - not_null
          - unique